// Generates TypeScript types and C# DTOs from level.schema.json (`make gen`).
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");
const repo = resolve(pkg, "../..");
const schemaPath = join(pkg, "level.schema.json");
const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

const banner = "// <auto-generated> from packages/level-schema/level.schema.json by `make gen`. Do not edit. </auto-generated>\n";

// TypeScript
const ts = await compile(schema, "LevelDto", {
  bannerComment: banner.trim(),
  additionalProperties: false,
  unreachableDefinitions: true,
  style: { singleQuote: false },
});
mkdirSync(join(pkg, "generated"), { recursive: true });
writeFileSync(join(pkg, "generated", "level.ts"), ts);

// C#: quicktype cannot handle `const`, so rewrite it as a single-value enum first.
function constToEnum(node) {
  if (Array.isArray(node)) return node.map(constToEnum);
  if (node && typeof node === "object") {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === "const") {
        out.enum = [v];
        if (typeof v === "number") out.type = "integer";
      } else out[k] = constToEnum(v);
    }
    return out;
  }
  return node;
}
const tmp = mkdtempSync(join(tmpdir(), "level-schema-"));
const tmpSchema = join(tmp, "level.schema.json");
writeFileSync(tmpSchema, JSON.stringify(constToEnum(schema)));
const csOut = join(repo, "apps/game/Assets/_Project/Scripts/CodingEngine/Levels/Generated/LevelDto.g.cs");
mkdirSync(dirname(csOut), { recursive: true });
execFileSync(
  join(repo, "node_modules/.bin/quicktype"),
  [
    "--src-lang", "schema", "--lang", "csharp",
    "--framework", "NewtonSoft",
    "--namespace", "Roboya.CodingEngine.Levels.Generated",
    "--top-level", "LevelDto",
    "--array-type", "list",
    "--features", "complete",
    "-o", csOut, tmpSchema,
  ],
  { stdio: "inherit" },
);
// Deterministic header (quicktype embeds usage text naming the temp file).
const cs = readFileSync(csOut, "utf8").replace(/^\/\/ <auto-generated \/>[\s\S]*?\n(?=namespace)/, banner + "\n");
writeFileSync(csOut, cs);
console.log("generated generated/level.ts and", csOut.replace(repo + "/", ""));
